### ISSUE TITLE
lua_openscript_cl doesn't work

### ISSUE THREAD

**Issue by raecyst** [qubard/Script-Enforcer-Bypass#1]
Trying to execute a script that'll print "hello" as a test, but haven't gotten any errors or any message. Don't know if I've done something wrong.

**Comment by qubard** [comment]
Are you using the dll from the releases page? That one is outdated. I've just updated it. If you follow the recommended installation guide it always should work.

**Comment by qubard** [comment]
I've closed the issue because I tested it and the patch still works.
