### ISSUE TITLE
Doesn't work on 64 bit branch (x86-64 Chromium + 64 bit binaries branch)

### ISSUE THREAD

**Issue by mastopgunaf** [qubard/Script-Enforcer-Bypass#2]
The title, basically, it only works if I select 32 bit when I'm launching Garry's Mod.
lua_openscript_cl simply does nothing on 64 bit Garry's Mod

**Comment by qubard** [comment]
Yeah I forgot to mention it only works on 32bit (x86). I prob wont be updating it for 64bit.
