### ISSUE TITLE
Python gives me issue when I paste patch.py text.

### ISSUE THREAD

**Issue by wweony23** [qubard/Script-Enforcer-Bypass#3]
Python send me this as respond:
 Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
FileNotFoundError: [Errno 2] No such file or directory: 'client.dll'
More details here:https://imgur.com/a/X8weJF1
P.S.I downloaded client.dll and puted it in C:\Program Files (x86)\Steam\steamapps\common\GarrysMod\bin.
I also have latest python version

**Comment by qubard** [comment]
run the script in the same directory as `client.dll`
